# -*- coding: utf-8 -*-
"""network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14XRKzzCqjtbAdIn8nktchRZZistkoV4t
"""

import heapq
import random
import networkx as nx
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
from collections import defaultdict
from dataclasses import dataclass, field

# ─────────────────────────
# 1. Packet
# ─────────────────────────
@dataclass
class Packet:
    packet_id: int
    src: int
    dst: int
    size_mb: float
    create_time: float

    current_node: int = field(init=False)
    path_taken: list = field(default_factory=list)
    total_delay: float = 0.0
    is_dropped: bool = False

    def __post_init__(self):
        self.current_node = self.src
        self.path_taken.append(self.src)


# ─────────────────────────
# 2. NSFNET
# ─────────────────────────
def build_nsfnet():
    G = nx.Graph()
    G.add_nodes_from(range(14))

    edges = [
        (0,1),(0,2),(0,7),(1,2),(1,3),(2,5),(3,4),(3,10),
        (4,5),(4,6),(5,9),(5,13),(6,7),(7,8),(8,9),(8,11),
        (9,10),(9,12),(10,11),(11,12),(12,13),
    ]

    # seed는 main()에서 통합 관리 (build_nsfnet 내부에서 고정하지 않음)
    for u, v in edges:
        G.add_edge(u, v,
                   bandwidth=random.uniform(100, 500),
                   delay=random.uniform(1, 10))
    return G


# ─────────────────────────
# 3. Traffic Generator
# ─────────────────────────
class TrafficGenerator:
    def __init__(self, graph, burst_ticks=range(100, 150)):
        self.graph = graph
        self.burst_ticks = burst_ticks
        self._pid = 0

    def generate(self, tick):
        packets = []
        nodes = list(self.graph.nodes)

        for _ in range(5):
            s, d = random.choice(nodes), random.choice(nodes)
            if s != d:
                packets.append(Packet(self._pid, s, d, 1, tick))
                self._pid += 1

        if tick in self.burst_ticks:
            for _ in range(40):
                s = random.choice([3, 9])
                d = random.choice(nodes)
                if s != d:
                    packets.append(Packet(self._pid, s, d, 2, tick))
                    self._pid += 1

        return packets


# ──────────────────────────────
# 4. 비선형 큐잉 지연 계산 함수
# ──────────────────────────────
def compute_queuing_delay(prop_delay, bandwidth, current_load):
    if bandwidth <= 0:
        return float('inf')
    rho = min(current_load / bandwidth, 0.9999)
    queuing_delay = prop_delay * (rho / (1.0 - rho))
    return prop_delay + queuing_delay


# ─────────────────────────
# 5. OSPF
# ─────────────────────────
class OSPFStatic:
    def __init__(self, graph, queue_capacity=10):
        self.graph = graph
        self.queue_capacity = queue_capacity
        self.queues = defaultdict(list)   # key: (현재노드, 다음노드) 링크별 독립 큐
        self._tick_drop_count = 0

        self.routing_table = self._build_routing_table()
        self._init_stats()
        self.link_load = defaultdict(float)

    # 대역폭 기반 비용으로 Dijkstra 실행
    def _dijkstra(self, source):
        dist = {n: float('inf') for n in self.graph.nodes}
        prev = {n: None for n in self.graph.nodes}
        dist[source] = 0
        heap = [(0, source)]

        while heap:
            d, u = heapq.heappop(heap)
            if d > dist[u]:
                continue
            for v in self.graph.neighbors(u):
                bw = self.graph[u][v]['bandwidth']
                cost = 10000.0 / bw      # 대역폭이 클수록 비용이 낮음
                nd = d + cost
                if nd < dist[v]:
                    dist[v] = nd
                    prev[v] = u
                    heapq.heappush(heap, (nd, v))
        return prev

    def _build_routing_table(self):
        table = defaultdict(dict)
        for s in self.graph.nodes:
            prev = self._dijkstra(s)
            for d in self.graph.nodes:
                if s == d:
                    continue
                path, cur = [], d
                while cur is not None:
                    path.append(cur)
                    cur = prev[cur]
                path.reverse()
                if path and path[0] == s:
                    table[s][d] = path[1]
        return table

    def get_next_hop(self, cur, dst):
        return self.routing_table.get(cur, {}).get(dst)

    def enqueue(self, node, pkt):
        # FIX: 목적지 도달 패킷은 enqueue 전에 처리해야 하므로
        # 여기서는 목적지가 아닌 패킷만 들어온다고 가정
        nxt = self.get_next_hop(node, pkt.dst)
        if nxt is None:
            pkt.is_dropped = True
            self.stats["dropped"] += 1
            self._tick_drop_count += 1
            return False

        q_key = (node, nxt)
        if len(self.queues[q_key]) >= self.queue_capacity:
            pkt.is_dropped = True
            self.stats["dropped"] += 1
            self._tick_drop_count += 1
            return False

        self.queues[q_key].append(pkt)
        return True

    def step(self, tick):
        self._tick_drop_count = 0

        link_bw = {}
        for u, v in self.graph.edges():
            bw = self.graph[u][v]['bandwidth']
            link_bw[(u, v)] = bw
            link_bw[(v, u)] = bw

        # FIX: 링크 사용량은 정규화된 단방향 키로만 기록
        self.link_load = defaultdict(float)

        delivered = 0
        delay_sum = 0.0

        # 처리 순서 랜덤화로 공평성 확보
        nodes = list(self.graph.nodes)
        random.shuffle(nodes)

        for node in nodes:
            out_hops = [k[1] for k in list(self.queues.keys()) if k[0] == node]
            random.shuffle(out_hops)

            for nxt in out_hops:
                q_key = (node, nxt)
                pending = []

                while self.queues[q_key]:
                    pkt = self.queues[q_key].pop(0)

                    # 목적지 도달 처리
                    if pkt.current_node == pkt.dst:
                        self.stats["delivered"] += 1
                        delay_sum += pkt.total_delay
                        delivered += 1
                        continue

                    edge_key = (pkt.current_node, nxt)

                    if link_bw[edge_key] >= pkt.size_mb:
                        prop_delay = self.graph[pkt.current_node][nxt]['delay']
                        bandwidth  = self.graph[pkt.current_node][nxt]['bandwidth']
                        current_load = bandwidth - link_bw[edge_key] + pkt.size_mb
                        hop_delay    = compute_queuing_delay(prop_delay, bandwidth, current_load)

                        link_bw[edge_key]                                    -= pkt.size_mb
                        link_bw[(nxt, pkt.current_node)]                     -= pkt.size_mb

                        # FIX: 단방향 정규화 키로만 기록 (이중 계산 방지)
                        norm_key = (min(pkt.current_node, nxt),
                                    max(pkt.current_node, nxt))
                        self.link_load[norm_key] += pkt.size_mb

                        pkt.current_node = nxt
                        pkt.path_taken.append(nxt)
                        pkt.total_delay += hop_delay

                        # 목적지가 아니면 다음 링크 큐에 삽입
                        if pkt.current_node != pkt.dst:
                            self.enqueue(nxt, pkt)
                        else:
                            # 목적지 도달: 다음 틱 처리를 위해 도착 큐에 넣음
                            # (delivered는 다음 step()에서 pop 시 처리됨)
                            # → 즉시 처리 방식으로 변경: 바로 카운트
                            self.stats["delivered"] += 1
                            delay_sum += pkt.total_delay
                            delivered += 1
                    else:
                        pending.append(pkt)

                # FIX: pop(0)으로 이미 큐가 비워졌으므로 pending만 남기면 됨
                self.queues[q_key] = pending

        avg_delay = delay_sum / delivered if delivered else 0.0

        # FIX: 정규화된 단방향 키로 사용률 계산 (이중 계산 제거)
        utilization_snapshot = {}
        for u, v in self.graph.edges():
            bw = self.graph[u][v]['bandwidth']
            norm_key = (min(u, v), max(u, v))
            load = self.link_load.get(norm_key, 0.0)
            utilization_snapshot[(u, v)] = min(load / bw, 1.0) if bw > 0 else 0.0

        self.tick_log.append({
            "tick":        tick,
            "dropped":     self._tick_drop_count,
            "delivered":   delivered,
            "avg_delay":   avg_delay,
            "utilization": utilization_snapshot,
        })

    def _init_stats(self):
        self.stats    = {"delivered": 0, "dropped": 0}
        self.tick_log = []


# ──────────────────────────────────────────────────────────────
# 6. 시각화
# ──────────────────────────────────────────────────────────────
def plot_tick_log(log):
    ticks = [x["tick"]      for x in log]
    drop  = [x["dropped"]   for x in log]
    delay = [x["avg_delay"] for x in log]

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 7), sharex=True)
    fig.suptitle("OSPF Static Routing – Per-Tick Performance", fontsize=14, fontweight='bold')

    ax1.fill_between(ticks, drop, alpha=0.3, color='tomato')
    ax1.plot(ticks, drop, color='tomato', linewidth=1.5, label='Packet Drop / tick')
    ax1.axvspan(100, 149, alpha=0.12, color='red', label='Burst Traffic (tick 100~149)')
    ax1.set_ylabel("Dropped Packets")
    ax1.legend(fontsize=9)
    ax1.grid(axis='y', linestyle='--', alpha=0.5)

    ax2.fill_between(ticks, delay, alpha=0.3, color='steelblue')
    ax2.plot(ticks, delay, color='steelblue', linewidth=1.5, label='Avg Delay (ms)')
    ax2.axvspan(100, 149, alpha=0.12, color='red', label='Burst Traffic (tick 100~149)')
    ax2.set_xlabel("Tick")
    ax2.set_ylabel("Avg E2E Delay (ms)")
    ax2.legend(fontsize=9)
    ax2.grid(axis='y', linestyle='--', alpha=0.5)

    plt.tight_layout()
    plt.show()


def plot_network_congestion(graph, tick_log, tick=None):
    if tick is None:
        entry = tick_log[-1]
    else:
        entry = next((x for x in tick_log if x["tick"] == tick), tick_log[-1])

    util_map = entry.get("utilization", {})
    pos = nx.spring_layout(graph, seed=7)

    edge_colors, edge_widths, edge_labels = [], [], {}

    for u, v in graph.edges():
        util = util_map.get((u, v), util_map.get((v, u), 0.0))

        if util <= 0.50:
            color, width = 'limegreen', 2.0
        elif util <= 0.80:
            color, width = 'orange', 3.5
        else:
            color, width = 'crimson', 5.5

        edge_colors.append(color)
        edge_widths.append(width)

        prop_d  = graph[u][v]['delay']
        bw      = graph[u][v]['bandwidth']
        load    = util * bw
        q_delay = compute_queuing_delay(prop_d, bw, load)
        edge_labels[(u, v)] = f"{util*100:.0f}%\n{q_delay:.1f}ms"

    fig, ax = plt.subplots(figsize=(13, 9))
    ax.set_title(
        f"NSFNET Congestion Map  |  Tick {entry['tick']}\n"
        f"Drop: {entry['dropped']}  |  Avg Delay: {entry['avg_delay']:.2f} ms",
        fontsize=13, fontweight='bold', pad=14
    )
    nx.draw_networkx_nodes(graph, pos, ax=ax,
                           node_color='#4A90D9', node_size=700, alpha=0.95)
    nx.draw_networkx_labels(graph, pos, ax=ax,
                            font_color='white', font_size=10, font_weight='bold')
    nx.draw_networkx_edges(graph, pos, ax=ax,
                           edge_color=edge_colors, width=edge_widths, alpha=0.85)
    nx.draw_networkx_edge_labels(graph, pos, edge_labels=edge_labels, ax=ax,
                                 font_size=7.5,
                                 bbox=dict(boxstyle='round,pad=0.2', fc='white', alpha=0.75))
    patches = [
        mpatches.Patch(color='limegreen', label='여유 (≤ 50%)'),
        mpatches.Patch(color='orange',    label='주의 (50~80%)'),
        mpatches.Patch(color='crimson',   label='혼잡 (> 80%)'),
    ]
    ax.legend(handles=patches, loc='lower left', fontsize=10, framealpha=0.9)
    ax.axis('off')
    plt.tight_layout()
    plt.show()


def plot_utilization_heatmap(graph, tick_log):
    edges   = list(graph.edges())
    n_ticks = len(tick_log)

    matrix = np.zeros((len(edges), n_ticks))
    for t_idx, entry in enumerate(tick_log):
        util_map = entry.get("utilization", {})
        for e_idx, (u, v) in enumerate(edges):
            matrix[e_idx, t_idx] = util_map.get((u, v), util_map.get((v, u), 0.0))

    fig, ax = plt.subplots(figsize=(14, 7))
    im = ax.imshow(matrix, aspect='auto', cmap='RdYlGn_r',
                   vmin=0, vmax=1, interpolation='nearest')
    ax.set_yticks(range(len(edges)))
    ax.set_yticklabels([f"{u}↔{v}" for u, v in edges], fontsize=8)
    ax.set_xlabel("Tick")
    ax.set_title("Link Utilization Heatmap  (Red = Congested, Green = Free)",
                 fontweight='bold')
    cbar = fig.colorbar(im, ax=ax, fraction=0.03, pad=0.02)
    cbar.set_label("Utilization", fontsize=10)
    ax.axvline(x=100, color='white', linewidth=1.5, linestyle='--', alpha=0.8)
    ax.axvline(x=149, color='white', linewidth=1.5, linestyle='--', alpha=0.8)
    # FIX: transAxes 좌표계 사용 (transData + y=-1.2 는 그래프 밖으로 나감)
    ax.text(0.54, 1.02, "← Burst →", ha='center', color='gray', fontsize=9,
            transform=ax.transAxes)
    plt.tight_layout()
    plt.show()


# ─────────────────────────
# 7. 실행
# ─────────────────────────
if __name__ == "__main__":
    random.seed(0)

    graph   = build_nsfnet()
    traffic = TrafficGenerator(graph)
    ospf    = OSPFStatic(graph)

    print("Simulating 200 ticks...")
    for t in range(200):
        for pkt in traffic.generate(t):
            ospf.enqueue(pkt.src, pkt)
        ospf.step(t)

    print(f"  Delivered : {ospf.stats['delivered']}")
    print(f"  Dropped   : {ospf.stats['dropped']}")
    total = ospf.stats['delivered'] + ospf.stats['dropped']
    print(f"  Drop Rate : {ospf.stats['dropped']/total*100:.1f}%" if total else "")

    plot_tick_log(ospf.tick_log)
    plot_network_congestion(graph, ospf.tick_log)
    plot_network_congestion(graph, ospf.tick_log, tick=120)
    plot_utilization_heatmap(graph, ospf.tick_log)