# -*- coding: utf-8 -*-
"""networkAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YDXgsgCso_ND222JKknqT5q7KUGclNWO
"""

import heapq
import random
import networkx as nx
import numpy as np
import gymnasium as gym
from gymnasium import spaces
from collections import defaultdict
from dataclasses import dataclass, field

# ─────────────────────────
# 1. Packet & Graph Builder
# ─────────────────────────
@dataclass
class Packet:
    packet_id: int
    src: int
    dst: int
    size_mb: float
    create_time: float
    current_node: int = field(init=False)
    path_taken: list = field(default_factory=list)
    total_delay: float = 0.0
    is_dropped: bool = False

    def __post_init__(self):
        self.current_node = self.src
        self.path_taken.append(self.src)


def build_nsfnet():
    G = nx.Graph()
    G.add_nodes_from(range(14))
    edges = [
        (0,1),(0,2),(0,7),(1,2),(1,3),(2,5),(3,4),(3,10),
        (4,5),(4,6),(5,9),(5,13),(6,7),(7,8),(8,9),(8,11),
        (9,10),(9,12),(10,11),(11,12),(12,13),
    ]
    for u, v in edges:
        G.add_edge(u, v,
                   bandwidth=random.uniform(100, 500),
                   delay=random.uniform(1, 10))
    return G


class TrafficGenerator:
    def __init__(self, graph, burst_ticks=range(100, 150)):
        self.graph = graph
        self.burst_ticks = burst_ticks
        self._pid = 0

    def generate(self, tick):
        packets = []
        nodes = list(self.graph.nodes)
        for _ in range(5):
            s, d = random.choice(nodes), random.choice(nodes)
            if s != d:
                packets.append(Packet(self._pid, s, d, 1, tick))
                self._pid += 1
        if tick in self.burst_ticks:
            for _ in range(40):
                s = random.choice([3, 9])
                d = random.choice(nodes)
                if s != d:
                    packets.append(Packet(self._pid, s, d, 2, tick))
                    self._pid += 1
        return packets


def compute_queuing_delay(prop_delay, bandwidth, current_load):
    if bandwidth <= 0:
        return float('inf')
    rho = min(current_load / bandwidth, 0.9999)
    return prop_delay + prop_delay * (rho / (1.0 - rho))


# ─────────────────────────
# 2. Dynamic Router
# ─────────────────────────
class DynamicRouter:
    def __init__(self, graph, queue_capacity=10):
        self.graph = graph
        self.queue_capacity = queue_capacity
        self.queues = defaultdict(list)
        self.routing_table = {}
        self.link_load = defaultdict(float)

    def update_routing_table(self, edge_weights):
        """
        AI가 결정한 링크별 가중치로 Dijkstra를 실행해 라우팅 테이블을 갱신.
        edge_weights: { (min_u, max_v): cost, ... }  ← 정규화된 키
        """
        table = defaultdict(dict)
        for s in self.graph.nodes:
            dist = {n: float('inf') for n in self.graph.nodes}
            prev = {n: None for n in self.graph.nodes}
            dist[s] = 0
            heap = [(0, s)]

            while heap:
                d, u = heapq.heappop(heap)
                if d > dist[u]:
                    continue
                for v in self.graph.neighbors(u):
                    norm_edge = (min(u, v), max(u, v))
                    cost = edge_weights.get(norm_edge, 1.0)
                    nd = d + cost
                    if nd < dist[v]:
                        dist[v] = nd
                        prev[v] = u
                        heapq.heappush(heap, (nd, v))

            for d in self.graph.nodes:
                if s == d:
                    continue
                path, cur = [], d
                while cur is not None:
                    path.append(cur)
                    cur = prev[cur]
                path.reverse()
                if path and path[0] == s:
                    table[s][d] = path[1]

        self.routing_table = table

    def enqueue(self, node, pkt):
        """
        패킷을 링크별 큐에 삽입.
        반환값: (성공 여부, 드랍 사유)
          - (True,  None)         : 정상 삽입
          - (False, 'no_route')   : 경로 없음
          - (False, 'queue_full') : 큐 포화
        """
        nxt = self.routing_table.get(node, {}).get(pkt.dst)
        if nxt is None:
            pkt.is_dropped = True
            return False, 'no_route'

        q_key = (node, nxt)
        if len(self.queues[q_key]) >= self.queue_capacity:
            pkt.is_dropped = True
            return False, 'queue_full'

        self.queues[q_key].append(pkt)
        return True, None

    def process_tick(self):
        """
        1틱 진행: 모든 링크 큐에서 패킷을 처리하고 결과를 반환.
        반환값: (delivered, dropped, avg_delay, util_map)
        """
        link_bw = {}
        for u, v in self.graph.edges():
            bw = self.graph[u][v]['bandwidth']
            link_bw[(u, v)] = bw
            link_bw[(v, u)] = bw

        self.link_load = defaultdict(float)
        delivered, dropped = 0, 0
        delay_sum = 0.0

        nodes = list(self.graph.nodes)
        random.shuffle(nodes)

        for node in nodes:
            out_hops = [k[1] for k in list(self.queues.keys()) if k[0] == node]
            random.shuffle(out_hops)

            for nxt in out_hops:
                q_key = (node, nxt)
                pending = []

                while self.queues[q_key]:
                    pkt = self.queues[q_key].pop(0)

                    # 목적지 도달
                    if pkt.current_node == pkt.dst:
                        delivered += 1
                        delay_sum += pkt.total_delay
                        continue

                    edge_key = (pkt.current_node, nxt)

                    if link_bw[edge_key] >= pkt.size_mb:
                        prop_d = self.graph[pkt.current_node][nxt]['delay']
                        bw     = self.graph[pkt.current_node][nxt]['bandwidth']
                        c_load = bw - link_bw[edge_key] + pkt.size_mb
                        hop_d  = compute_queuing_delay(prop_d, bw, c_load)

                        link_bw[edge_key]                        -= pkt.size_mb
                        link_bw[(nxt, pkt.current_node)]         -= pkt.size_mb
                        norm_key = (min(pkt.current_node, nxt),
                                    max(pkt.current_node, nxt))
                        self.link_load[norm_key]                 += pkt.size_mb

                        pkt.current_node = nxt
                        pkt.path_taken.append(nxt)
                        pkt.total_delay  += hop_d

                        if pkt.current_node != pkt.dst:
                            # FIX: enqueue 반환값으로 드랍 카운트
                            success, _ = self.enqueue(nxt, pkt)
                            if not success:
                                dropped += 1
                        else:
                            delivered += 1
                            delay_sum += pkt.total_delay
                    else:
                        pending.append(pkt)

                self.queues[q_key] = pending

        avg_delay = delay_sum / delivered if delivered else 0.0

        util_map = {}
        for u, v in self.graph.edges():
            bw = self.graph[u][v]['bandwidth']
            norm_key = (min(u, v), max(u, v))
            load = self.link_load.get(norm_key, 0.0)
            util_map[norm_key] = min(load / bw, 1.0) if bw > 0 else 0.0

        return delivered, dropped, avg_delay, util_map


# ─────────────────────────
# 3. Gymnasium Environment
# ─────────────────────────
class NSFNetEnv(gym.Env):
    """
    NSFNet 기반 강화학습 환경 (Gymnasium 표준)

    [Action]  : 각 링크(엣지)의 Dijkstra 비용 가중치 벡터 (shape: 21,)
                값이 클수록 해당 링크를 회피하는 경로가 선택됨
                범위: 1.0 ~ 100.0

    [Obs]     : 각 링크의 현재 사용률 벡터 (shape: 21,)
                0.0 = 여유, 1.0 = 포화

    [Reward]  : delivered - dropped * 10 - avg_delay * 0.1
                (팀원이 가중치 튜닝 필요)

    [Episode] : 200틱 = 1에피소드
    """
    metadata = {"render_modes": ["human"]}

    def __init__(self, graph_seed=42):
        super().__init__()

        # FIX: 그래프를 고정 seed로 한 번만 생성
        # → 에피소드마다 같은 네트워크 토폴로지 사용 (공정한 비교)
        random.seed(graph_seed)
        self.graph = build_nsfnet()

        self.edges    = list(self.graph.edges())
        self.num_edges = len(self.edges)
        self.max_ticks = 200

        self.action_space = spaces.Box(
            low=1.0, high=100.0,
            shape=(self.num_edges,), dtype=np.float32
        )
        self.observation_space = spaces.Box(
            low=0.0, high=1.0,
            shape=(self.num_edges,), dtype=np.float32
        )

        # 라우팅 테이블 갱신 주기 (틱)
        # FIX: 매 틱마다 Dijkstra 재계산은 과부하
        # → N틱마다 한 번만 갱신 (협의해서 조정)
        self.routing_update_interval = 5

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)

        # 트래픽·라우터만 초기화 (그래프는 고정)
        if seed is not None:
            random.seed(seed)

        self.current_tick = 0
        self.traffic      = TrafficGenerator(self.graph)
        self.router       = DynamicRouter(self.graph)

        # 초기 라우팅 테이블: 균등 가중치
        initial_weights = {
            (min(u,v), max(u,v)): 1.0
            for u, v in self.edges
        }
        self.router.update_routing_table(initial_weights)

        obs  = np.zeros(self.num_edges, dtype=np.float32)
        info = {}
        return obs, info

    def step(self, action):
        # FIX: N틱마다만 라우팅 테이블 갱신 (Dijkstra 과호출 방지)
        if self.current_tick % self.routing_update_interval == 0:
            edge_weights = {
                (min(self.edges[i][0], self.edges[i][1]),
                 max(self.edges[i][0], self.edges[i][1])): float(action[i])
                for i in range(self.num_edges)
            }
            self.router.update_routing_table(edge_weights)

        # 트래픽 발생 및 인큐
        # FIX: 초기 enqueue 드랍도 카운트
        init_dropped = 0
        for pkt in self.traffic.generate(self.current_tick):
            success, _ = self.router.enqueue(pkt.src, pkt)
            if not success:
                init_dropped += 1

        # 1틱 시뮬레이션
        delivered, dropped, avg_delay, util_map = self.router.process_tick()
        total_dropped = dropped + init_dropped

        # Observation
        obs = np.array([
            util_map.get(
                (min(e[0],e[1]), max(e[0],e[1])), 0.0
            )
            for e in self.edges
        ], dtype=np.float32)

        # Reward
        # 설계한 가중치로 교체 필요
        reward = (
            delivered   * 1.0
            - total_dropped * 10.0
            - avg_delay     * 0.1
        )

        self.current_tick += 1
        terminated = self.current_tick >= self.max_ticks
        truncated  = False

        info = {
            "tick":          self.current_tick,
            "delivered":     delivered,
            "dropped":       total_dropped,
            "avg_delay":     avg_delay,
        }

        return obs, reward, terminated, truncated, info


# ─────────────────────────
# 4. 실행 테스트
# ─────────────────────────
if __name__ == "__main__":
    env = NSFNetEnv(graph_seed=42)
    obs, info = env.reset(seed=0)
    total_reward = 0

    print("강화학습 환경 테스트 시작...")
    print(f"  Action 차원  : {env.action_space.shape}")
    print(f"  Obs 차원     : {env.observation_space.shape}")

    done = False
    while not done:
        action = env.action_space.sample()
        next_obs, reward, terminated, truncated, info = env.step(action)
        total_reward += reward
        done = terminated or truncated

    print(f"\n시뮬레이션 종료 ({info['tick']} 틱)")
    print(f"  Total Reward : {total_reward:.2f}")
    print(f"  전달         : {info['delivered']}")
    print(f"  드랍         : {info['dropped']}")
    print(f"  평균 지연    : {info['avg_delay']:.2f} ms")
    env.close()